// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: buildpb.proto

package buildpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FieldType int32

const (
	FieldType_Unkown     FieldType = 0
	FieldType_BaseType   FieldType = 1
	FieldType_ListType   FieldType = 2
	FieldType_MapType    FieldType = 3
	FieldType_CustomType FieldType = 4
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "Unkown",
		1: "BaseType",
		2: "ListType",
		3: "MapType",
		4: "CustomType",
	}
	FieldType_value = map[string]int32{
		"Unkown":     0,
		"BaseType":   1,
		"ListType":   2,
		"MapType":    3,
		"CustomType": 4,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_buildpb_proto_enumTypes[0].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_buildpb_proto_enumTypes[0]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{0}
}

type BaseTypeDesc int32

const (
	BaseTypeDesc_Int8    BaseTypeDesc = 0
	BaseTypeDesc_Uint8   BaseTypeDesc = 1
	BaseTypeDesc_Int16   BaseTypeDesc = 2
	BaseTypeDesc_Uint16  BaseTypeDesc = 3
	BaseTypeDesc_Int32   BaseTypeDesc = 4
	BaseTypeDesc_Uint32  BaseTypeDesc = 5
	BaseTypeDesc_Int64   BaseTypeDesc = 6
	BaseTypeDesc_Uint64  BaseTypeDesc = 7
	BaseTypeDesc_String  BaseTypeDesc = 8
	BaseTypeDesc_Binary  BaseTypeDesc = 9
	BaseTypeDesc_Bool    BaseTypeDesc = 10
	BaseTypeDesc_Float32 BaseTypeDesc = 11
	BaseTypeDesc_Float64 BaseTypeDesc = 12
)

// Enum value maps for BaseTypeDesc.
var (
	BaseTypeDesc_name = map[int32]string{
		0:  "Int8",
		1:  "Uint8",
		2:  "Int16",
		3:  "Uint16",
		4:  "Int32",
		5:  "Uint32",
		6:  "Int64",
		7:  "Uint64",
		8:  "String",
		9:  "Binary",
		10: "Bool",
		11: "Float32",
		12: "Float64",
	}
	BaseTypeDesc_value = map[string]int32{
		"Int8":    0,
		"Uint8":   1,
		"Int16":   2,
		"Uint16":  3,
		"Int32":   4,
		"Uint32":  5,
		"Int64":   6,
		"Uint64":  7,
		"String":  8,
		"Binary":  9,
		"Bool":    10,
		"Float32": 11,
		"Float64": 12,
	}
)

func (x BaseTypeDesc) Enum() *BaseTypeDesc {
	p := new(BaseTypeDesc)
	*p = x
	return p
}

func (x BaseTypeDesc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseTypeDesc) Descriptor() protoreflect.EnumDescriptor {
	return file_buildpb_proto_enumTypes[1].Descriptor()
}

func (BaseTypeDesc) Type() protoreflect.EnumType {
	return &file_buildpb_proto_enumTypes[1]
}

func (x BaseTypeDesc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseTypeDesc.Descriptor instead.
func (BaseTypeDesc) EnumDescriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{1}
}

type BuildRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 需要生成的原文件名
	Files []string `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	// 文件详细信息
	Programs map[string]*FileDesc `protobuf:"bytes,2,rep,name=Programs,proto3" json:"Programs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *BuildRQ) Reset() {
	*x = BuildRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRQ) ProtoMessage() {}

func (x *BuildRQ) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRQ.ProtoReflect.Descriptor instead.
func (*BuildRQ) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{0}
}

func (x *BuildRQ) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BuildRQ) GetPrograms() map[string]*FileDesc {
	if x != nil {
		return x.Programs
	}
	return nil
}

type BuildOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *BuildOutput) Reset() {
	*x = BuildOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildOutput) ProtoMessage() {}

func (x *BuildOutput) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildOutput.ProtoReflect.Descriptor instead.
func (*BuildOutput) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{1}
}

func (x *BuildOutput) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *BuildOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BuildRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*BuildOutput `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
}

func (x *BuildRS) Reset() {
	*x = BuildRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRS) ProtoMessage() {}

func (x *BuildRS) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRS.ProtoReflect.Descriptor instead.
func (*BuildRS) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{2}
}

func (x *BuildRS) GetResult() []*BuildOutput {
	if x != nil {
		return x.Result
	}
	return nil
}

type FileDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File string `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	// 包名
	Pkg *PackageDesc `protobuf:"bytes,2,opt,name=Pkg,proto3" json:"Pkg,omitempty"`
	// 依赖文件
	Imports []*ImportDesc `protobuf:"bytes,3,rep,name=Imports,proto3" json:"Imports,omitempty"`
	// 文件选项
	Options *OptionDesc `protobuf:"bytes,4,opt,name=Options,proto3" json:"Options,omitempty"`
	// 枚举
	Enums []*EnumDesc `protobuf:"bytes,5,rep,name=Enums,proto3" json:"Enums,omitempty"`
	// 消息
	Msgs []*MsgDesc `protobuf:"bytes,6,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
	// 服务
	Services []*ServiceDesc `protobuf:"bytes,7,rep,name=Services,proto3" json:"Services,omitempty"`
	// 项目
	Projects []*ProjectDesc `protobuf:"bytes,8,rep,name=Projects,proto3" json:"Projects,omitempty"`
}

func (x *FileDesc) Reset() {
	*x = FileDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDesc) ProtoMessage() {}

func (x *FileDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDesc.ProtoReflect.Descriptor instead.
func (*FileDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{3}
}

func (x *FileDesc) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *FileDesc) GetPkg() *PackageDesc {
	if x != nil {
		return x.Pkg
	}
	return nil
}

func (x *FileDesc) GetImports() []*ImportDesc {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *FileDesc) GetOptions() *OptionDesc {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *FileDesc) GetEnums() []*EnumDesc {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *FileDesc) GetMsgs() []*MsgDesc {
	if x != nil {
		return x.Msgs
	}
	return nil
}

func (x *FileDesc) GetServices() []*ServiceDesc {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *FileDesc) GetProjects() []*ProjectDesc {
	if x != nil {
		return x.Projects
	}
	return nil
}

type DocDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Doc []string `protobuf:"bytes,1,rep,name=Doc,proto3" json:"Doc,omitempty"`
}

func (x *DocDesc) Reset() {
	*x = DocDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocDesc) ProtoMessage() {}

func (x *DocDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocDesc.ProtoReflect.Descriptor instead.
func (*DocDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{4}
}

func (x *DocDesc) GetDoc() []string {
	if x != nil {
		return x.Doc
	}
	return nil
}

type PackageDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 包名
	Package string `protobuf:"bytes,1,opt,name=Package,proto3" json:"Package,omitempty"`
	// 包注释
	Doc *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
}

func (x *PackageDesc) Reset() {
	*x = PackageDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageDesc) ProtoMessage() {}

func (x *PackageDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageDesc.ProtoReflect.Descriptor instead.
func (*PackageDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{5}
}

func (x *PackageDesc) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *PackageDesc) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

type ImportDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 注释
	Doc *DocDesc `protobuf:"bytes,1,opt,name=Doc,proto3" json:"Doc,omitempty"`
	// 别名
	Alias string `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	// 文件名
	File string `protobuf:"bytes,3,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *ImportDesc) Reset() {
	*x = ImportDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportDesc) ProtoMessage() {}

func (x *ImportDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportDesc.ProtoReflect.Descriptor instead.
func (*ImportDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{6}
}

func (x *ImportDesc) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *ImportDesc) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ImportDesc) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// 选项数值
type OptionValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    string `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	IntValue int64  `protobuf:"varint,2,opt,name=IntValue,proto3" json:"IntValue,omitempty"`
	// 注释
	Doc *DocDesc `protobuf:"bytes,3,opt,name=Doc,proto3" json:"Doc,omitempty"`
}

func (x *OptionValue) Reset() {
	*x = OptionValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionValue) ProtoMessage() {}

func (x *OptionValue) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionValue.ProtoReflect.Descriptor instead.
func (*OptionValue) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{7}
}

func (x *OptionValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OptionValue) GetIntValue() int64 {
	if x != nil {
		return x.IntValue
	}
	return 0
}

func (x *OptionValue) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

// 选项定义
type OptionDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 文件选项
	Options map[string]*OptionValue `protobuf:"bytes,1,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *OptionDesc) Reset() {
	*x = OptionDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OptionDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionDesc) ProtoMessage() {}

func (x *OptionDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionDesc.ProtoReflect.Descriptor instead.
func (*OptionDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{8}
}

func (x *OptionDesc) GetOptions() map[string]*OptionValue {
	if x != nil {
		return x.Options
	}
	return nil
}

// 枚举数值
type EnumValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 注释
	Doc   *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
	Value int64    `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *EnumValue) Reset() {
	*x = EnumValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumValue) ProtoMessage() {}

func (x *EnumValue) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumValue.ProtoReflect.Descriptor instead.
func (*EnumValue) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{9}
}

func (x *EnumValue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumValue) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *EnumValue) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 枚举定义
type EnumDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 注释
	Doc *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
	// 文件选项
	Options *OptionDesc  `protobuf:"bytes,3,opt,name=Options,proto3" json:"Options,omitempty"`
	Values  []*EnumValue `protobuf:"bytes,4,rep,name=Values,proto3" json:"Values,omitempty"`
}

func (x *EnumDesc) Reset() {
	*x = EnumDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumDesc) ProtoMessage() {}

func (x *EnumDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumDesc.ProtoReflect.Descriptor instead.
func (*EnumDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{10}
}

func (x *EnumDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumDesc) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *EnumDesc) GetOptions() *OptionDesc {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *EnumDesc) GetValues() []*EnumValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type TypeDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type FieldType `protobuf:"varint,1,opt,name=Type,proto3,enum=buildpb.FieldType" json:"Type,omitempty"`
	// Type = BaseType,CustomType
	// 使用 Key
	// Type = ListType
	// 使用 Key 根据ElemCustom判断 数组元素是自定义类型还是基础类型
	// Type = MapType
	// Key 是基础类型. Value 根据ElemCustom判断 数组元素是自定义类型还是基础类型
	Key   string `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	// 元素 是基础类型还是自定义类型
	ElemCustom bool `protobuf:"varint,4,opt,name=ElemCustom,proto3" json:"ElemCustom,omitempty"`
	// 基础类型 和Key/Value 同时填充
	KeyBase   BaseTypeDesc `protobuf:"varint,5,opt,name=KeyBase,proto3,enum=buildpb.BaseTypeDesc" json:"KeyBase,omitempty"`
	ValueBase BaseTypeDesc `protobuf:"varint,6,opt,name=ValueBase,proto3,enum=buildpb.BaseTypeDesc" json:"ValueBase,omitempty"`
	// 关联自定义类型
	Msg *MsgDesc `protobuf:"bytes,7,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *TypeDesc) Reset() {
	*x = TypeDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDesc) ProtoMessage() {}

func (x *TypeDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDesc.ProtoReflect.Descriptor instead.
func (*TypeDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{11}
}

func (x *TypeDesc) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_Unkown
}

func (x *TypeDesc) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TypeDesc) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TypeDesc) GetElemCustom() bool {
	if x != nil {
		return x.ElemCustom
	}
	return false
}

func (x *TypeDesc) GetKeyBase() BaseTypeDesc {
	if x != nil {
		return x.KeyBase
	}
	return BaseTypeDesc_Int8
}

func (x *TypeDesc) GetValueBase() BaseTypeDesc {
	if x != nil {
		return x.ValueBase
	}
	return BaseTypeDesc_Int8
}

func (x *TypeDesc) GetMsg() *MsgDesc {
	if x != nil {
		return x.Msg
	}
	return nil
}

type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 注释
	Doc *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
	// 文件选项
	Options *OptionDesc `protobuf:"bytes,3,opt,name=Options,proto3" json:"Options,omitempty"`
	// 字段序号
	No int32 `protobuf:"varint,4,opt,name=No,proto3" json:"No,omitempty"`
	// 字段类型
	Type *TypeDesc `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{12}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *Field) GetOptions() *OptionDesc {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Field) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *Field) GetType() *TypeDesc {
	if x != nil {
		return x.Type
	}
	return nil
}

type MsgDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 注释
	Doc *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
	// 文件选项
	Options *OptionDesc `protobuf:"bytes,3,opt,name=Options,proto3" json:"Options,omitempty"`
	// 字段
	Fields []*Field `protobuf:"bytes,4,rep,name=Fields,proto3" json:"Fields,omitempty"`
}

func (x *MsgDesc) Reset() {
	*x = MsgDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDesc) ProtoMessage() {}

func (x *MsgDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDesc.ProtoReflect.Descriptor instead.
func (*MsgDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{13}
}

func (x *MsgDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgDesc) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *MsgDesc) GetOptions() *OptionDesc {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MsgDesc) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

type MethodDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 注释
	Doc *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
	// 文件选项
	Options *OptionDesc `protobuf:"bytes,3,opt,name=Options,proto3" json:"Options,omitempty"`
	//
	Request *MsgDesc `protobuf:"bytes,4,opt,name=Request,proto3" json:"Request,omitempty"`
	Reply   *MsgDesc `protobuf:"bytes,5,opt,name=Reply,proto3" json:"Reply,omitempty"`
	//
	MethodID int64 `protobuf:"varint,6,opt,name=MethodID,proto3" json:"MethodID,omitempty"`
}

func (x *MethodDesc) Reset() {
	*x = MethodDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodDesc) ProtoMessage() {}

func (x *MethodDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodDesc.ProtoReflect.Descriptor instead.
func (*MethodDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{14}
}

func (x *MethodDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodDesc) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *MethodDesc) GetOptions() *OptionDesc {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *MethodDesc) GetRequest() *MsgDesc {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *MethodDesc) GetReply() *MsgDesc {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *MethodDesc) GetMethodID() int64 {
	if x != nil {
		return x.MethodID
	}
	return 0
}

type ServiceDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 注释
	Doc *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
	// 文件选项
	Options *OptionDesc `protobuf:"bytes,3,opt,name=Options,proto3" json:"Options,omitempty"`
	// 方法集合
	Methods []*MethodDesc `protobuf:"bytes,4,rep,name=Methods,proto3" json:"Methods,omitempty"`
}

func (x *ServiceDesc) Reset() {
	*x = ServiceDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDesc) ProtoMessage() {}

func (x *ServiceDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDesc.ProtoReflect.Descriptor instead.
func (*ServiceDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{15}
}

func (x *ServiceDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDesc) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *ServiceDesc) GetOptions() *OptionDesc {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ServiceDesc) GetMethods() []*MethodDesc {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ProjectDesc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// 注释
	Doc *DocDesc `protobuf:"bytes,2,opt,name=Doc,proto3" json:"Doc,omitempty"`
	// 文件选项
	Conf map[string]*OptionDesc `protobuf:"bytes,3,rep,name=Conf,proto3" json:"Conf,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProjectDesc) Reset() {
	*x = ProjectDesc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buildpb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDesc) ProtoMessage() {}

func (x *ProjectDesc) ProtoReflect() protoreflect.Message {
	mi := &file_buildpb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDesc.ProtoReflect.Descriptor instead.
func (*ProjectDesc) Descriptor() ([]byte, []int) {
	return file_buildpb_proto_rawDescGZIP(), []int{16}
}

func (x *ProjectDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectDesc) GetDoc() *DocDesc {
	if x != nil {
		return x.Doc
	}
	return nil
}

func (x *ProjectDesc) GetConf() map[string]*OptionDesc {
	if x != nil {
		return x.Conf
	}
	return nil
}

var File_buildpb_proto protoreflect.FileDescriptor

var file_buildpb_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x22, 0xab, 0x01, 0x0a, 0x07, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x51, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x08, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x51, 0x2e, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x50, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x4e, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x35, 0x0a, 0x0b, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a,
	0x07, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x53, 0x12, 0x2c, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x70, 0x62, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0xd7, 0x02, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x03, 0x50, 0x6b, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x50, 0x6b, 0x67, 0x12,
	0x2d, 0x0a, 0x07, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x12, 0x2d,
	0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x27, 0x0a,
	0x05, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x44, 0x65, 0x73, 0x63, 0x52,
	0x05, 0x45, 0x6e, 0x75, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4d,
	0x73, 0x67, 0x44, 0x65, 0x73, 0x63, 0x52, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x12, 0x30, 0x0a, 0x08,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x65, 0x73, 0x63, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x30,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x22, 0x1b, 0x0a, 0x07, 0x44, 0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x44,
	0x6f, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x22, 0x4b, 0x0a,
	0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x18, 0x0a, 0x07,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x44, 0x6f,
	0x63, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x22, 0x5a, 0x0a, 0x0a, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e,
	0x44, 0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x14, 0x0a, 0x05,
	0x41, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x41, 0x6c, 0x69,
	0x61, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x63, 0x0a, 0x0b, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x49,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x49,
	0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x44,
	0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x22, 0x9a, 0x01, 0x0a, 0x0a,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x12, 0x3a, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63,
	0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x50, 0x0a, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70,
	0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x59, 0x0a, 0x09, 0x45, 0x6e, 0x75, 0x6d,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62,
	0x2e, 0x44, 0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x14, 0x0a,
	0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x08, 0x45, 0x6e, 0x75, 0x6d, 0x44, 0x65, 0x73, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x44,
	0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x2d, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70,
	0x62, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x22, 0x84, 0x02, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x12, 0x26, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6c, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x45, 0x6c, 0x65, 0x6d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x12, 0x2f, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x42, 0x61, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x4b, 0x65, 0x79, 0x42, 0x61, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x61, 0x73, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x52, 0x09, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4d, 0x73,
	0x67, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0xa5, 0x01, 0x0a, 0x05, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e,
	0x44, 0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x2d, 0x0a, 0x07,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x52, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4e,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4e, 0x6f, 0x12, 0x25, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x70, 0x62, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x73, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x44, 0x65, 0x73,
	0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x2d, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70,
	0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0xe3, 0x01,
	0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x44, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x52,
	0x03, 0x44, 0x6f, 0x63, 0x12, 0x2d, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4d,
	0x73, 0x67, 0x44, 0x65, 0x73, 0x63, 0x52, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x26, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x65, 0x73, 0x63,
	0x52, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x49, 0x44, 0x22, 0xa3, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x6f, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x44,
	0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f, 0x63, 0x12, 0x2d, 0x0a, 0x07, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73,
	0x63, 0x52, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x44, 0x65, 0x73, 0x63,
	0x52, 0x07, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0xc7, 0x01, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x65, 0x73, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a,
	0x03, 0x44, 0x6f, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x75, 0x69,
	0x6c, 0x64, 0x70, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x44, 0x65, 0x73, 0x63, 0x52, 0x03, 0x44, 0x6f,
	0x63, 0x12, 0x32, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x66, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x44, 0x65, 0x73, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x04, 0x43, 0x6f, 0x6e, 0x66, 0x1a, 0x4c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x2e, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x2a, 0x50, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x6b, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08,
	0x42, 0x61, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x04, 0x2a, 0xa4, 0x01, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x6e, 0x74, 0x38, 0x10, 0x00,
	0x12, 0x09, 0x0a, 0x05, 0x55, 0x69, 0x6e, 0x74, 0x38, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49,
	0x6e, 0x74, 0x31, 0x36, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x31, 0x36,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x6e, 0x74,
	0x36, 0x34, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x10, 0x07,
	0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c,
	0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x10, 0x0b, 0x12,
	0x0b, 0x0a, 0x07, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x10, 0x0c, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x67, 0x72, 0x6f,
	0x6e, 0x6d, 0x61, 0x67, 0x69, 0x2f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6c, 0x2f, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buildpb_proto_rawDescOnce sync.Once
	file_buildpb_proto_rawDescData = file_buildpb_proto_rawDesc
)

func file_buildpb_proto_rawDescGZIP() []byte {
	file_buildpb_proto_rawDescOnce.Do(func() {
		file_buildpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_buildpb_proto_rawDescData)
	})
	return file_buildpb_proto_rawDescData
}

var file_buildpb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_buildpb_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_buildpb_proto_goTypes = []interface{}{
	(FieldType)(0),      // 0: buildpb.FieldType
	(BaseTypeDesc)(0),   // 1: buildpb.BaseTypeDesc
	(*BuildRQ)(nil),     // 2: buildpb.BuildRQ
	(*BuildOutput)(nil), // 3: buildpb.BuildOutput
	(*BuildRS)(nil),     // 4: buildpb.BuildRS
	(*FileDesc)(nil),    // 5: buildpb.FileDesc
	(*DocDesc)(nil),     // 6: buildpb.DocDesc
	(*PackageDesc)(nil), // 7: buildpb.PackageDesc
	(*ImportDesc)(nil),  // 8: buildpb.ImportDesc
	(*OptionValue)(nil), // 9: buildpb.OptionValue
	(*OptionDesc)(nil),  // 10: buildpb.OptionDesc
	(*EnumValue)(nil),   // 11: buildpb.EnumValue
	(*EnumDesc)(nil),    // 12: buildpb.EnumDesc
	(*TypeDesc)(nil),    // 13: buildpb.TypeDesc
	(*Field)(nil),       // 14: buildpb.Field
	(*MsgDesc)(nil),     // 15: buildpb.MsgDesc
	(*MethodDesc)(nil),  // 16: buildpb.MethodDesc
	(*ServiceDesc)(nil), // 17: buildpb.ServiceDesc
	(*ProjectDesc)(nil), // 18: buildpb.ProjectDesc
	nil,                 // 19: buildpb.BuildRQ.ProgramsEntry
	nil,                 // 20: buildpb.OptionDesc.OptionsEntry
	nil,                 // 21: buildpb.ProjectDesc.ConfEntry
}
var file_buildpb_proto_depIdxs = []int32{
	19, // 0: buildpb.BuildRQ.Programs:type_name -> buildpb.BuildRQ.ProgramsEntry
	3,  // 1: buildpb.BuildRS.Result:type_name -> buildpb.BuildOutput
	7,  // 2: buildpb.FileDesc.Pkg:type_name -> buildpb.PackageDesc
	8,  // 3: buildpb.FileDesc.Imports:type_name -> buildpb.ImportDesc
	10, // 4: buildpb.FileDesc.Options:type_name -> buildpb.OptionDesc
	12, // 5: buildpb.FileDesc.Enums:type_name -> buildpb.EnumDesc
	15, // 6: buildpb.FileDesc.Msgs:type_name -> buildpb.MsgDesc
	17, // 7: buildpb.FileDesc.Services:type_name -> buildpb.ServiceDesc
	18, // 8: buildpb.FileDesc.Projects:type_name -> buildpb.ProjectDesc
	6,  // 9: buildpb.PackageDesc.Doc:type_name -> buildpb.DocDesc
	6,  // 10: buildpb.ImportDesc.Doc:type_name -> buildpb.DocDesc
	6,  // 11: buildpb.OptionValue.Doc:type_name -> buildpb.DocDesc
	20, // 12: buildpb.OptionDesc.Options:type_name -> buildpb.OptionDesc.OptionsEntry
	6,  // 13: buildpb.EnumValue.Doc:type_name -> buildpb.DocDesc
	6,  // 14: buildpb.EnumDesc.Doc:type_name -> buildpb.DocDesc
	10, // 15: buildpb.EnumDesc.Options:type_name -> buildpb.OptionDesc
	11, // 16: buildpb.EnumDesc.Values:type_name -> buildpb.EnumValue
	0,  // 17: buildpb.TypeDesc.Type:type_name -> buildpb.FieldType
	1,  // 18: buildpb.TypeDesc.KeyBase:type_name -> buildpb.BaseTypeDesc
	1,  // 19: buildpb.TypeDesc.ValueBase:type_name -> buildpb.BaseTypeDesc
	15, // 20: buildpb.TypeDesc.Msg:type_name -> buildpb.MsgDesc
	6,  // 21: buildpb.Field.Doc:type_name -> buildpb.DocDesc
	10, // 22: buildpb.Field.Options:type_name -> buildpb.OptionDesc
	13, // 23: buildpb.Field.Type:type_name -> buildpb.TypeDesc
	6,  // 24: buildpb.MsgDesc.Doc:type_name -> buildpb.DocDesc
	10, // 25: buildpb.MsgDesc.Options:type_name -> buildpb.OptionDesc
	14, // 26: buildpb.MsgDesc.Fields:type_name -> buildpb.Field
	6,  // 27: buildpb.MethodDesc.Doc:type_name -> buildpb.DocDesc
	10, // 28: buildpb.MethodDesc.Options:type_name -> buildpb.OptionDesc
	15, // 29: buildpb.MethodDesc.Request:type_name -> buildpb.MsgDesc
	15, // 30: buildpb.MethodDesc.Reply:type_name -> buildpb.MsgDesc
	6,  // 31: buildpb.ServiceDesc.Doc:type_name -> buildpb.DocDesc
	10, // 32: buildpb.ServiceDesc.Options:type_name -> buildpb.OptionDesc
	16, // 33: buildpb.ServiceDesc.Methods:type_name -> buildpb.MethodDesc
	6,  // 34: buildpb.ProjectDesc.Doc:type_name -> buildpb.DocDesc
	21, // 35: buildpb.ProjectDesc.Conf:type_name -> buildpb.ProjectDesc.ConfEntry
	5,  // 36: buildpb.BuildRQ.ProgramsEntry.value:type_name -> buildpb.FileDesc
	9,  // 37: buildpb.OptionDesc.OptionsEntry.value:type_name -> buildpb.OptionValue
	10, // 38: buildpb.ProjectDesc.ConfEntry.value:type_name -> buildpb.OptionDesc
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_buildpb_proto_init() }
func file_buildpb_proto_init() {
	if File_buildpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buildpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OptionDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buildpb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectDesc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buildpb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buildpb_proto_goTypes,
		DependencyIndexes: file_buildpb_proto_depIdxs,
		EnumInfos:         file_buildpb_proto_enumTypes,
		MessageInfos:      file_buildpb_proto_msgTypes,
	}.Build()
	File_buildpb_proto = out.File
	file_buildpb_proto_rawDesc = nil
	file_buildpb_proto_goTypes = nil
	file_buildpb_proto_depIdxs = nil
}
