// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"github.com/aggronmagi/wctl/protocol/token"
)

const (
	NoState    = -1
	NumStates  = 124
	NumSymbols = 150
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '.'
1: 'p'
2: 'a'
3: 'c'
4: 'k'
5: 'a'
6: 'g'
7: 'e'
8: ';'
9: ','
10: 'i'
11: 'm'
12: 'p'
13: 'o'
14: 'r'
15: 't'
16: '='
17: 'e'
18: 'n'
19: 'u'
20: 'm'
21: '{'
22: '}'
23: 'm'
24: 'e'
25: 's'
26: 's'
27: 'a'
28: 'g'
29: 'e'
30: '['
31: ']'
32: 'm'
33: 'a'
34: 'p'
35: 'i'
36: 'n'
37: 't'
38: '8'
39: 'u'
40: 'i'
41: 'n'
42: 't'
43: '8'
44: 'i'
45: 'n'
46: 't'
47: '1'
48: '6'
49: 'u'
50: 'i'
51: 'n'
52: 't'
53: '1'
54: '6'
55: 'i'
56: 'n'
57: 't'
58: '3'
59: '2'
60: 'u'
61: 'i'
62: 'n'
63: 't'
64: '3'
65: '2'
66: 'i'
67: 'n'
68: 't'
69: '6'
70: '4'
71: 'u'
72: 'i'
73: 'n'
74: 't'
75: '6'
76: '4'
77: 's'
78: 't'
79: 'r'
80: 'i'
81: 'n'
82: 'g'
83: 'b'
84: 'y'
85: 't'
86: 'e'
87: 's'
88: 'b'
89: 'o'
90: 'o'
91: 'l'
92: 's'
93: 'e'
94: 'r'
95: 'v'
96: 'i'
97: 'c'
98: 'e'
99: 'o'
100: 'n'
101: 'e'
102: 'w'
103: 'a'
104: 'y'
105: ':'
106: 'n'
107: 'o'
108: 't'
109: 'i'
110: 'f'
111: 'y'
112: 't'
113: 'w'
114: 'o'
115: 'w'
116: 'a'
117: 'y'
118: '('
119: ')'
120: 'p'
121: 'r'
122: 'o'
123: 'j'
124: 'e'
125: 'c'
126: 't'
127: '+'
128: '-'
129: '_'
130: '/'
131: '*'
132: '*'
133: '/'
134: '/'
135: '/'
136: '\n'
137: '`'
138: '`'
139: '"'
140: '"'
141: ' '
142: '\t'
143: '\n'
144: '\r'
145: '#'
146: '\n'
147: '0'-'9'
148: 'a'-'z'
149: .
*/
