// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 2
		case r == 35: // ['#','#']
			return 3
		case r == 40: // ['(','(']
			return 4
		case r == 41: // [')',')']
			return 5
		case r == 43: // ['+','+']
			return 6
		case r == 44: // [',',',']
			return 7
		case r == 45: // ['-','-']
			return 6
		case r == 47: // ['/','/']
			return 8
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		case r == 58: // [':',':']
			return 10
		case r == 59: // [';',';']
			return 11
		case r == 61: // ['=','=']
			return 12
		case r == 91: // ['[','[']
			return 13
		case r == 93: // [']',']']
			return 14
		case r == 95: // ['_','_']
			return 15
		case r == 96: // ['`','`']
			return 16
		case r == 97: // ['a','a']
			return 15
		case r == 98: // ['b','b']
			return 17
		case 99 <= r && r <= 100: // ['c','d']
			return 15
		case r == 101: // ['e','e']
			return 18
		case 102 <= r && r <= 104: // ['f','h']
			return 15
		case r == 105: // ['i','i']
			return 19
		case 106 <= r && r <= 108: // ['j','l']
			return 15
		case r == 109: // ['m','m']
			return 20
		case r == 110: // ['n','n']
			return 21
		case r == 111: // ['o','o']
			return 22
		case r == 112: // ['p','p']
			return 23
		case 113 <= r && r <= 114: // ['q','r']
			return 15
		case r == 115: // ['s','s']
			return 24
		case r == 116: // ['t','t']
			return 25
		case r == 117: // ['u','u']
			return 26
		case 118 <= r && r <= 122: // ['v','z']
			return 15
		case r == 123: // ['{','{']
			return 27
		case r == 125: // ['}','}']
			return 28
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 29
		default:
			return 2
		}
	},
	// S3
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 30
		default:
			return 3
		}
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 31
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 32
		case r == 47: // ['/','/']
			return 33
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case r == 96: // ['`','`']
			return 37
		default:
			return 16
		}
	},
	// S17
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 110: // ['a','n']
			return 36
		case r == 111: // ['o','o']
			return 38
		case 112 <= r && r <= 120: // ['p','x']
			return 36
		case r == 121: // ['y','y']
			return 39
		case r == 122: // ['z','z']
			return 36
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 109: // ['a','m']
			return 36
		case r == 110: // ['n','n']
			return 40
		case 111 <= r && r <= 122: // ['o','z']
			return 36
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 108: // ['a','l']
			return 36
		case r == 109: // ['m','m']
			return 41
		case r == 110: // ['n','n']
			return 42
		case 111 <= r && r <= 122: // ['o','z']
			return 36
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case r == 97: // ['a','a']
			return 43
		case 98 <= r && r <= 100: // ['b','d']
			return 36
		case r == 101: // ['e','e']
			return 44
		case 102 <= r && r <= 122: // ['f','z']
			return 36
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 110: // ['a','n']
			return 36
		case r == 111: // ['o','o']
			return 45
		case 112 <= r && r <= 122: // ['p','z']
			return 36
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 109: // ['a','m']
			return 36
		case r == 110: // ['n','n']
			return 46
		case 111 <= r && r <= 122: // ['o','z']
			return 36
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case r == 97: // ['a','a']
			return 47
		case 98 <= r && r <= 113: // ['b','q']
			return 36
		case r == 114: // ['r','r']
			return 48
		case 115 <= r && r <= 122: // ['s','z']
			return 36
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 100: // ['a','d']
			return 36
		case r == 101: // ['e','e']
			return 49
		case 102 <= r && r <= 115: // ['f','s']
			return 36
		case r == 116: // ['t','t']
			return 50
		case 117 <= r && r <= 122: // ['u','z']
			return 36
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 118: // ['a','v']
			return 36
		case r == 119: // ['w','w']
			return 51
		case 120 <= r && r <= 122: // ['x','z']
			return 36
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 104: // ['a','h']
			return 36
		case r == 105: // ['i','i']
			return 52
		case 106 <= r && r <= 122: // ['j','z']
			return 36
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 31
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 53
		default:
			return 32
		}
	},
	// S33
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 54
		default:
			return 33
		}
	},
	// S34
	func(r rune) int {
		switch {
		case r == 95: // ['_','_']
			return 55
		case 97 <= r && r <= 122: // ['a','z']
			return 55
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 110: // ['a','n']
			return 36
		case r == 111: // ['o','o']
			return 56
		case 112 <= r && r <= 122: // ['p','z']
			return 36
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 115: // ['a','s']
			return 36
		case r == 116: // ['t','t']
			return 57
		case 117 <= r && r <= 122: // ['u','z']
			return 36
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 116: // ['a','t']
			return 36
		case r == 117: // ['u','u']
			return 58
		case 118 <= r && r <= 122: // ['v','z']
			return 36
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 111: // ['a','o']
			return 36
		case r == 112: // ['p','p']
			return 59
		case 113 <= r && r <= 122: // ['q','z']
			return 36
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 115: // ['a','s']
			return 36
		case r == 116: // ['t','t']
			return 60
		case 117 <= r && r <= 122: // ['u','z']
			return 36
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 111: // ['a','o']
			return 36
		case r == 112: // ['p','p']
			return 61
		case 113 <= r && r <= 122: // ['q','z']
			return 36
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 114: // ['a','r']
			return 36
		case r == 115: // ['s','s']
			return 62
		case 116 <= r && r <= 122: // ['t','z']
			return 36
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 115: // ['a','s']
			return 36
		case r == 116: // ['t','t']
			return 63
		case 117 <= r && r <= 122: // ['u','z']
			return 36
		}
		return NoState
	},
	// S46
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 100: // ['a','d']
			return 36
		case r == 101: // ['e','e']
			return 64
		case 102 <= r && r <= 122: // ['f','z']
			return 36
		}
		return NoState
	},
	// S47
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 98: // ['a','b']
			return 36
		case r == 99: // ['c','c']
			return 65
		case 100 <= r && r <= 122: // ['d','z']
			return 36
		}
		return NoState
	},
	// S48
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 110: // ['a','n']
			return 36
		case r == 111: // ['o','o']
			return 66
		case 112 <= r && r <= 122: // ['p','z']
			return 36
		}
		return NoState
	},
	// S49
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 113: // ['a','q']
			return 36
		case r == 114: // ['r','r']
			return 67
		case 115 <= r && r <= 122: // ['s','z']
			return 36
		}
		return NoState
	},
	// S50
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 113: // ['a','q']
			return 36
		case r == 114: // ['r','r']
			return 68
		case 115 <= r && r <= 122: // ['s','z']
			return 36
		}
		return NoState
	},
	// S51
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 110: // ['a','n']
			return 36
		case r == 111: // ['o','o']
			return 69
		case 112 <= r && r <= 122: // ['p','z']
			return 36
		}
		return NoState
	},
	// S52
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 109: // ['a','m']
			return 36
		case r == 110: // ['n','n']
			return 70
		case 111 <= r && r <= 122: // ['o','z']
			return 36
		}
		return NoState
	},
	// S53
	func(r rune) int {
		switch {
		case r == 47: // ['/','/']
			return 71
		}
		return NoState
	},
	// S54
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S55
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		case r == 95: // ['_','_']
			return 73
		case 97 <= r && r <= 122: // ['a','z']
			return 73
		}
		return NoState
	},
	// S56
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 107: // ['a','k']
			return 36
		case r == 108: // ['l','l']
			return 74
		case 109 <= r && r <= 122: // ['m','z']
			return 36
		}
		return NoState
	},
	// S57
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 100: // ['a','d']
			return 36
		case r == 101: // ['e','e']
			return 75
		case 102 <= r && r <= 122: // ['f','z']
			return 36
		}
		return NoState
	},
	// S58
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 108: // ['a','l']
			return 36
		case r == 109: // ['m','m']
			return 76
		case 110 <= r && r <= 122: // ['n','z']
			return 36
		}
		return NoState
	},
	// S59
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 110: // ['a','n']
			return 36
		case r == 111: // ['o','o']
			return 77
		case 112 <= r && r <= 122: // ['p','z']
			return 36
		}
		return NoState
	},
	// S60
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case r == 48: // ['0','0']
			return 35
		case r == 49: // ['1','1']
			return 78
		case r == 50: // ['2','2']
			return 35
		case r == 51: // ['3','3']
			return 79
		case 52 <= r && r <= 53: // ['4','5']
			return 35
		case r == 54: // ['6','6']
			return 80
		case r == 55: // ['7','7']
			return 35
		case r == 56: // ['8','8']
			return 81
		case r == 57: // ['9','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S61
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S62
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 114: // ['a','r']
			return 36
		case r == 115: // ['s','s']
			return 82
		case 116 <= r && r <= 122: // ['t','z']
			return 36
		}
		return NoState
	},
	// S63
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 104: // ['a','h']
			return 36
		case r == 105: // ['i','i']
			return 83
		case 106 <= r && r <= 122: // ['j','z']
			return 36
		}
		return NoState
	},
	// S64
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 118: // ['a','v']
			return 36
		case r == 119: // ['w','w']
			return 84
		case 120 <= r && r <= 122: // ['x','z']
			return 36
		}
		return NoState
	},
	// S65
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 106: // ['a','j']
			return 36
		case r == 107: // ['k','k']
			return 85
		case 108 <= r && r <= 122: // ['l','z']
			return 36
		}
		return NoState
	},
	// S66
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 105: // ['a','i']
			return 36
		case r == 106: // ['j','j']
			return 86
		case 107 <= r && r <= 122: // ['k','z']
			return 36
		}
		return NoState
	},
	// S67
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 117: // ['a','u']
			return 36
		case r == 118: // ['v','v']
			return 87
		case 119 <= r && r <= 122: // ['w','z']
			return 36
		}
		return NoState
	},
	// S68
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 104: // ['a','h']
			return 36
		case r == 105: // ['i','i']
			return 88
		case 106 <= r && r <= 122: // ['j','z']
			return 36
		}
		return NoState
	},
	// S69
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 118: // ['a','v']
			return 36
		case r == 119: // ['w','w']
			return 89
		case 120 <= r && r <= 122: // ['x','z']
			return 36
		}
		return NoState
	},
	// S70
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 115: // ['a','s']
			return 36
		case r == 116: // ['t','t']
			return 90
		case 117 <= r && r <= 122: // ['u','z']
			return 36
		}
		return NoState
	},
	// S71
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S72
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		case r == 95: // ['_','_']
			return 73
		case 97 <= r && r <= 122: // ['a','z']
			return 73
		}
		return NoState
	},
	// S73
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 72
		case r == 95: // ['_','_']
			return 73
		case 97 <= r && r <= 122: // ['a','z']
			return 73
		}
		return NoState
	},
	// S74
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S75
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 114: // ['a','r']
			return 36
		case r == 115: // ['s','s']
			return 91
		case 116 <= r && r <= 122: // ['t','z']
			return 36
		}
		return NoState
	},
	// S76
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S77
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 113: // ['a','q']
			return 36
		case r == 114: // ['r','r']
			return 92
		case 115 <= r && r <= 122: // ['s','z']
			return 36
		}
		return NoState
	},
	// S78
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 53: // ['0','5']
			return 35
		case r == 54: // ['6','6']
			return 93
		case 55 <= r && r <= 57: // ['7','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S79
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 49: // ['0','1']
			return 35
		case r == 50: // ['2','2']
			return 94
		case 51 <= r && r <= 57: // ['3','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S80
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 51: // ['0','3']
			return 35
		case r == 52: // ['4','4']
			return 95
		case 53 <= r && r <= 57: // ['5','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S81
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S82
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case r == 97: // ['a','a']
			return 96
		case 98 <= r && r <= 122: // ['b','z']
			return 36
		}
		return NoState
	},
	// S83
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 101: // ['a','e']
			return 36
		case r == 102: // ['f','f']
			return 97
		case 103 <= r && r <= 122: // ['g','z']
			return 36
		}
		return NoState
	},
	// S84
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case r == 97: // ['a','a']
			return 98
		case 98 <= r && r <= 122: // ['b','z']
			return 36
		}
		return NoState
	},
	// S85
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case r == 97: // ['a','a']
			return 99
		case 98 <= r && r <= 122: // ['b','z']
			return 36
		}
		return NoState
	},
	// S86
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 100: // ['a','d']
			return 36
		case r == 101: // ['e','e']
			return 100
		case 102 <= r && r <= 122: // ['f','z']
			return 36
		}
		return NoState
	},
	// S87
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 104: // ['a','h']
			return 36
		case r == 105: // ['i','i']
			return 101
		case 106 <= r && r <= 122: // ['j','z']
			return 36
		}
		return NoState
	},
	// S88
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 109: // ['a','m']
			return 36
		case r == 110: // ['n','n']
			return 102
		case 111 <= r && r <= 122: // ['o','z']
			return 36
		}
		return NoState
	},
	// S89
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case r == 97: // ['a','a']
			return 103
		case 98 <= r && r <= 122: // ['b','z']
			return 36
		}
		return NoState
	},
	// S90
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case r == 48: // ['0','0']
			return 35
		case r == 49: // ['1','1']
			return 104
		case r == 50: // ['2','2']
			return 35
		case r == 51: // ['3','3']
			return 105
		case 52 <= r && r <= 53: // ['4','5']
			return 35
		case r == 54: // ['6','6']
			return 106
		case r == 55: // ['7','7']
			return 35
		case r == 56: // ['8','8']
			return 107
		case r == 57: // ['9','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S91
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S92
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 115: // ['a','s']
			return 36
		case r == 116: // ['t','t']
			return 108
		case 117 <= r && r <= 122: // ['u','z']
			return 36
		}
		return NoState
	},
	// S93
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S94
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S95
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S96
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 102: // ['a','f']
			return 36
		case r == 103: // ['g','g']
			return 109
		case 104 <= r && r <= 122: // ['h','z']
			return 36
		}
		return NoState
	},
	// S97
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 120: // ['a','x']
			return 36
		case r == 121: // ['y','y']
			return 110
		case r == 122: // ['z','z']
			return 36
		}
		return NoState
	},
	// S98
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 120: // ['a','x']
			return 36
		case r == 121: // ['y','y']
			return 111
		case r == 122: // ['z','z']
			return 36
		}
		return NoState
	},
	// S99
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 102: // ['a','f']
			return 36
		case r == 103: // ['g','g']
			return 112
		case 104 <= r && r <= 122: // ['h','z']
			return 36
		}
		return NoState
	},
	// S100
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 98: // ['a','b']
			return 36
		case r == 99: // ['c','c']
			return 113
		case 100 <= r && r <= 122: // ['d','z']
			return 36
		}
		return NoState
	},
	// S101
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 98: // ['a','b']
			return 36
		case r == 99: // ['c','c']
			return 114
		case 100 <= r && r <= 122: // ['d','z']
			return 36
		}
		return NoState
	},
	// S102
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 102: // ['a','f']
			return 36
		case r == 103: // ['g','g']
			return 115
		case 104 <= r && r <= 122: // ['h','z']
			return 36
		}
		return NoState
	},
	// S103
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 120: // ['a','x']
			return 36
		case r == 121: // ['y','y']
			return 116
		case r == 122: // ['z','z']
			return 36
		}
		return NoState
	},
	// S104
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 53: // ['0','5']
			return 35
		case r == 54: // ['6','6']
			return 117
		case 55 <= r && r <= 57: // ['7','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S105
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 49: // ['0','1']
			return 35
		case r == 50: // ['2','2']
			return 118
		case 51 <= r && r <= 57: // ['3','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S106
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 51: // ['0','3']
			return 35
		case r == 52: // ['4','4']
			return 119
		case 53 <= r && r <= 57: // ['5','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S107
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S108
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S109
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 100: // ['a','d']
			return 36
		case r == 101: // ['e','e']
			return 120
		case 102 <= r && r <= 122: // ['f','z']
			return 36
		}
		return NoState
	},
	// S110
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S111
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S112
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 100: // ['a','d']
			return 36
		case r == 101: // ['e','e']
			return 121
		case 102 <= r && r <= 122: // ['f','z']
			return 36
		}
		return NoState
	},
	// S113
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 115: // ['a','s']
			return 36
		case r == 116: // ['t','t']
			return 122
		case 117 <= r && r <= 122: // ['u','z']
			return 36
		}
		return NoState
	},
	// S114
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 100: // ['a','d']
			return 36
		case r == 101: // ['e','e']
			return 123
		case 102 <= r && r <= 122: // ['f','z']
			return 36
		}
		return NoState
	},
	// S115
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S116
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S117
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S118
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S119
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S120
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S121
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S122
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
	// S123
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 34
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		case r == 95: // ['_','_']
			return 36
		case 97 <= r && r <= 122: // ['a','z']
			return 36
		}
		return NoState
	},
}
