// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // ;
			shift(3), // syntax
			nil,      // =
			nil,      // tok_literal
			nil,      // package
			nil,      // tok_identifier
			nil,      // import
			nil,      // enum
			nil,      // {
			nil,      // }
			nil,      // tok_num
			nil,      // option
			nil,      // message
			nil,      // map
			nil,      // <
			nil,      // ,
			nil,      // >
			nil,      // repeated
			nil,      // service
			nil,      // rpc
			nil,      // (
			nil,      // )
			nil,      // returns
			nil,      // tok_doc
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // ␚
			nil,          // empty
			nil,          // ;
			nil,          // syntax
			nil,          // =
			nil,          // tok_literal
			nil,          // package
			nil,          // tok_identifier
			nil,          // import
			nil,          // enum
			nil,          // {
			nil,          // }
			nil,          // tok_num
			nil,          // option
			nil,          // message
			nil,          // map
			nil,          // <
			nil,          // ,
			nil,          // >
			nil,          // repeated
			nil,          // service
			nil,          // rpc
			nil,          // (
			nil,          // )
			nil,          // returns
			nil,          // tok_doc
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // ;
			nil,      // syntax
			nil,      // =
			nil,      // tok_literal
			shift(5), // package
			nil,      // tok_identifier
			nil,      // import
			nil,      // enum
			nil,      // {
			nil,      // }
			nil,      // tok_num
			nil,      // option
			nil,      // message
			nil,      // map
			nil,      // <
			nil,      // ,
			nil,      // >
			nil,      // repeated
			nil,      // service
			nil,      // rpc
			nil,      // (
			nil,      // )
			nil,      // returns
			nil,      // tok_doc
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // ;
			nil,      // syntax
			shift(6), // =
			nil,      // tok_literal
			nil,      // package
			nil,      // tok_identifier
			nil,      // import
			nil,      // enum
			nil,      // {
			nil,      // }
			nil,      // tok_num
			nil,      // option
			nil,      // message
			nil,      // map
			nil,      // <
			nil,      // ,
			nil,      // >
			nil,      // repeated
			nil,      // service
			nil,      // rpc
			nil,      // (
			nil,      // )
			nil,      // returns
			nil,      // tok_doc
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // ␚, reduce: Imports
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(6), // import, reduce: Imports
			reduce(6), // enum, reduce: Imports
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(6), // option, reduce: Imports
			reduce(6), // message, reduce: Imports
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(6), // service, reduce: Imports
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // ;
			nil,      // syntax
			nil,      // =
			nil,      // tok_literal
			nil,      // package
			shift(8), // tok_identifier
			nil,      // import
			nil,      // enum
			nil,      // {
			nil,      // }
			nil,      // tok_num
			nil,      // option
			nil,      // message
			nil,      // map
			nil,      // <
			nil,      // ,
			nil,      // >
			nil,      // repeated
			nil,      // service
			nil,      // rpc
			nil,      // (
			nil,      // )
			nil,      // returns
			nil,      // tok_doc
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // ␚
			nil,      // empty
			nil,      // ;
			nil,      // syntax
			nil,      // =
			shift(9), // tok_literal
			nil,      // package
			nil,      // tok_identifier
			nil,      // import
			nil,      // enum
			nil,      // {
			nil,      // }
			nil,      // tok_num
			nil,      // option
			nil,      // message
			nil,      // map
			nil,      // <
			nil,      // ,
			nil,      // >
			nil,      // repeated
			nil,      // service
			nil,      // rpc
			nil,      // (
			nil,      // )
			nil,      // returns
			nil,      // tok_doc
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(10), // ␚, reduce: Defines
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			shift(12),  // import
			reduce(10), // enum, reduce: Defines
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(10), // option, reduce: Defines
			reduce(10), // message, reduce: Defines
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(10), // service, reduce: Defines
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: OptEnd
			nil,       // empty
			shift(14), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(2), // import, reduce: OptEnd
			reduce(2), // enum, reduce: OptEnd
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(2), // option, reduce: OptEnd
			reduce(2), // message, reduce: OptEnd
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(2), // service, reduce: OptEnd
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(15), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // ␚, reduce: ProtocolDefine
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			shift(21), // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			shift(22), // option
			shift(23), // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			shift(24), // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(7), // ␚, reduce: Imports
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(7), // import, reduce: Imports
			reduce(7), // enum, reduce: Imports
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(7), // option, reduce: Imports
			reduce(7), // message, reduce: Imports
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(7), // service, reduce: Imports
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			shift(25), // tok_literal
			nil,       // package
			shift(26), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // ␚, reduce: Package
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(5), // import, reduce: Package
			reduce(5), // enum, reduce: Package
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(5), // option, reduce: Package
			reduce(5), // message, reduce: Package
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(5), // service, reduce: Package
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: OptEnd
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(3), // import, reduce: OptEnd
			reduce(3), // enum, reduce: OptEnd
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(3), // option, reduce: OptEnd
			reduce(3), // message, reduce: OptEnd
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(3), // service, reduce: OptEnd
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			reduce(4), // package, reduce: Syntax
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(11), // ␚, reduce: Defines
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(11), // enum, reduce: Defines
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(11), // option, reduce: Defines
			reduce(11), // message, reduce: Defines
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(11), // service, reduce: Defines
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(12), // ␚, reduce: Define
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(12), // enum, reduce: Define
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(12), // option, reduce: Define
			reduce(12), // message, reduce: Define
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(12), // service, reduce: Define
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(13), // ␚, reduce: Define
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(13), // enum, reduce: Define
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(13), // option, reduce: Define
			reduce(13), // message, reduce: Define
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(13), // service, reduce: Define
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(14), // ␚, reduce: Define
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(14), // enum, reduce: Define
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(14), // option, reduce: Define
			reduce(14), // message, reduce: Define
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(14), // service, reduce: Define
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(15), // ␚, reduce: Define
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(15), // enum, reduce: Define
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(15), // option, reduce: Define
			reduce(15), // message, reduce: Define
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(15), // service, reduce: Define
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(27), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(28), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(29), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(30), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: OptEnd
			nil,       // empty
			shift(14), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(2), // import, reduce: OptEnd
			reduce(2), // enum, reduce: OptEnd
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(2), // option, reduce: OptEnd
			reduce(2), // message, reduce: OptEnd
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(2), // service, reduce: OptEnd
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			shift(32), // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			shift(33), // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			shift(34), // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			shift(35), // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			shift(36), // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(8), // ␚, reduce: Import
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(8), // import, reduce: Import
			reduce(8), // enum, reduce: Import
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(8), // option, reduce: Import
			reduce(8), // message, reduce: Import
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(8), // service, reduce: Import
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: OptEnd
			nil,       // empty
			shift(14), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(2), // import, reduce: OptEnd
			reduce(2), // enum, reduce: OptEnd
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(2), // option, reduce: OptEnd
			reduce(2), // message, reduce: OptEnd
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(2), // service, reduce: OptEnd
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(17), // tok_identifier, reduce: EnumValues
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(17), // }, reduce: EnumValues
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			shift(39), // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(24), // tok_identifier, reduce: Fields
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(24), // }, reduce: Fields
			nil,        // tok_num
			nil,        // option
			reduce(24), // message, reduce: Fields
			reduce(24), // map, reduce: Fields
			nil,        // <
			nil,        // ,
			nil,        // >
			reduce(24), // repeated, reduce: Fields
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(32), // }, reduce: ServiceElements
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			reduce(32), // rpc, reduce: ServiceElements
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(9), // ␚, reduce: Import
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			reduce(9), // import, reduce: Import
			reduce(9), // enum, reduce: Import
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(9), // option, reduce: Import
			reduce(9), // message, reduce: Import
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(9), // service, reduce: Import
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(42), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			shift(43), // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(45), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(46), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			shift(48), // }
			nil,       // tok_num
			nil,       // option
			shift(49), // message
			shift(52), // map
			nil,       // <
			nil,       // ,
			nil,       // >
			shift(53), // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			shift(54), // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			shift(56), // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(20), // ;, reduce: OptionValue
			nil,        // syntax
			shift(57),  // =
			nil,        // tok_literal
			nil,        // package
			reduce(20), // tok_identifier, reduce: OptionValue
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(20), // }, reduce: OptionValue
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: OptEnd
			nil,       // empty
			shift(60), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			reduce(2), // enum, reduce: OptEnd
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(2), // option, reduce: OptEnd
			reduce(2), // message, reduce: OptEnd
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(2), // service, reduce: OptEnd
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(18), // tok_identifier, reduce: EnumValues
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(18), // }, reduce: EnumValues
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(22), // ␚, reduce: Option
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(22), // enum, reduce: Option
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(22), // option, reduce: Option
			reduce(22), // message, reduce: Option
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(22), // service, reduce: Option
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(30), // tok_identifier, reduce: FieldType
			nil,        // import
			nil,        // enum
			nil,        // {
			nil,        // }
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(26), // tok_identifier, reduce: Fields
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(26), // }, reduce: Fields
			nil,        // tok_num
			nil,        // option
			reduce(26), // message, reduce: Fields
			reduce(26), // map, reduce: Fields
			nil,        // <
			nil,        // ,
			nil,        // >
			reduce(26), // repeated, reduce: Fields
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // ␚, reduce: OptEnd
			nil,       // empty
			shift(60), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			reduce(2), // enum, reduce: OptEnd
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(2), // option, reduce: OptEnd
			reduce(2), // message, reduce: OptEnd
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(2), // service, reduce: OptEnd
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(62), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(25), // tok_identifier, reduce: Fields
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(25), // }, reduce: Fields
			nil,        // tok_num
			nil,        // option
			reduce(25), // message, reduce: Fields
			reduce(25), // map, reduce: Fields
			nil,        // <
			nil,        // ,
			nil,        // >
			reduce(25), // repeated, reduce: Fields
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(63), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			shift(64), // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(65), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(31), // ␚, reduce: Service
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(31), // enum, reduce: Service
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(31), // option, reduce: Service
			reduce(31), // message, reduce: Service
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(31), // service, reduce: Service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(33), // }, reduce: ServiceElements
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			reduce(33), // rpc, reduce: ServiceElements
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(66), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			shift(67), // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(69), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			reduce(2), // tok_identifier, reduce: OptEnd
			nil,       // import
			nil,       // enum
			nil,       // {
			reduce(2), // }, reduce: OptEnd
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // ␚, reduce: Enum
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(16), // enum, reduce: Enum
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(16), // option, reduce: Enum
			reduce(16), // message, reduce: Enum
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(16), // service, reduce: Enum
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // ␚, reduce: OptEnd
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			reduce(3), // enum, reduce: OptEnd
			nil,       // {
			nil,       // }
			nil,       // tok_num
			reduce(3), // option, reduce: OptEnd
			reduce(3), // message, reduce: OptEnd
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			reduce(3), // service, reduce: OptEnd
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(23), // ␚, reduce: Message
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			reduce(23), // enum, reduce: Message
			nil,        // {
			nil,        // }
			nil,        // tok_num
			reduce(23), // option, reduce: Message
			reduce(23), // message, reduce: Message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			reduce(23), // service, reduce: Message
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			shift(70), // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			shift(71), // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(72), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(29), // tok_identifier, reduce: FieldType
			nil,        // import
			nil,        // enum
			nil,        // {
			nil,        // }
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			shift(73), // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			reduce(21), // ;, reduce: OptionValue
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(21), // tok_identifier, reduce: OptionValue
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(21), // }, reduce: OptionValue
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(19), // tok_identifier, reduce: EnumValue
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(19), // }, reduce: EnumValue
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			reduce(3), // tok_identifier, reduce: OptEnd
			nil,       // import
			nil,       // enum
			nil,       // {
			reduce(3), // }, reduce: OptEnd
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(24), // tok_identifier, reduce: Fields
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(24), // }, reduce: Fields
			nil,        // tok_num
			nil,        // option
			reduce(24), // message, reduce: Fields
			reduce(24), // map, reduce: Fields
			nil,        // <
			nil,        // ,
			nil,        // >
			reduce(24), // repeated, reduce: Fields
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			shift(75), // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			shift(76), // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(77), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(46), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			shift(78), // }
			nil,       // tok_num
			nil,       // option
			shift(49), // message
			shift(52), // map
			nil,       // <
			nil,       // ,
			nil,       // >
			shift(53), // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(80), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			reduce(2), // tok_identifier, reduce: OptEnd
			nil,       // import
			nil,       // enum
			nil,       // {
			reduce(2), // }, reduce: OptEnd
			nil,       // tok_num
			nil,       // option
			reduce(2), // message, reduce: OptEnd
			reduce(2), // map, reduce: OptEnd
			nil,       // <
			nil,       // ,
			nil,       // >
			reduce(2), // repeated, reduce: OptEnd
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(81), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			shift(82), // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			shift(80), // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			reduce(2), // tok_identifier, reduce: OptEnd
			nil,       // import
			nil,       // enum
			nil,       // {
			reduce(2), // }, reduce: OptEnd
			nil,       // tok_num
			nil,       // option
			reduce(2), // message, reduce: OptEnd
			reduce(2), // map, reduce: OptEnd
			nil,       // <
			nil,       // ,
			nil,       // >
			reduce(2), // repeated, reduce: OptEnd
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(27), // tok_identifier, reduce: FieldExpr
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(27), // }, reduce: FieldExpr
			nil,        // tok_num
			nil,        // option
			reduce(27), // message, reduce: FieldExpr
			reduce(27), // map, reduce: FieldExpr
			nil,        // <
			nil,        // ,
			nil,        // >
			reduce(27), // repeated, reduce: FieldExpr
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			reduce(3), // tok_identifier, reduce: OptEnd
			nil,       // import
			nil,       // enum
			nil,       // {
			reduce(3), // }, reduce: OptEnd
			nil,       // tok_num
			nil,       // option
			reduce(3), // message, reduce: OptEnd
			reduce(3), // map, reduce: OptEnd
			nil,       // <
			nil,       // ,
			nil,       // >
			reduce(3), // repeated, reduce: OptEnd
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			shift(84), // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			shift(85), // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(23), // tok_identifier, reduce: Message
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(23), // }, reduce: Message
			nil,        // tok_num
			nil,        // option
			reduce(23), // message, reduce: Message
			reduce(23), // map, reduce: Message
			nil,        // <
			nil,        // ,
			nil,        // >
			reduce(23), // repeated, reduce: Message
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			reduce(28), // tok_identifier, reduce: FieldType
			nil,        // import
			nil,        // enum
			nil,        // {
			nil,        // }
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			nil,        // rpc
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			shift(86), // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			shift(87), // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			shift(88), // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			shift(89), // {
			nil,       // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // ␚
			nil,       // empty
			nil,       // ;
			nil,       // syntax
			nil,       // =
			nil,       // tok_literal
			nil,       // package
			nil,       // tok_identifier
			nil,       // import
			nil,       // enum
			nil,       // {
			shift(90), // }
			nil,       // tok_num
			nil,       // option
			nil,       // message
			nil,       // map
			nil,       // <
			nil,       // ,
			nil,       // >
			nil,       // repeated
			nil,       // service
			nil,       // rpc
			nil,       // (
			nil,       // )
			nil,       // returns
			nil,       // tok_doc
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // ␚
			nil,        // empty
			nil,        // ;
			nil,        // syntax
			nil,        // =
			nil,        // tok_literal
			nil,        // package
			nil,        // tok_identifier
			nil,        // import
			nil,        // enum
			nil,        // {
			reduce(34), // }, reduce: Method
			nil,        // tok_num
			nil,        // option
			nil,        // message
			nil,        // map
			nil,        // <
			nil,        // ,
			nil,        // >
			nil,        // repeated
			nil,        // service
			reduce(34), // rpc, reduce: Method
			nil,        // (
			nil,        // )
			nil,        // returns
			nil,        // tok_doc
		},
	},
}
